### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by davecastlevania** [joshpetras/jammming#3]
https://github.com/joshpetras/jammming/blob/master/src/components/App/App.js#L56-L65

          <SearchBar onSearch={this.search} connected={this.state.connected}/>

Search does not appear, not sure if it is supposed to appear if connected but it just doesn't get past this part for us. Disabling us from testing it.

**Comment by joshpetras** [comment]
Hi Dave,
Very strange. Everything works fine on my laptop. As a test I just cloned my github repo into a new folder and ran npm install to build it from scratch.  Then upon running npm start to run the test environment, everything works as expected. You can also test the functionality on the live site at https://joshpetras.github.io/jammming/

One thing that may be preventing you from running it properly is the fact that my latest version of the code is configured to deploy to my github pages site. If you want to run the full test environment at "localhost:3000" then you will need to modify 4 lines of code in the "Spotify.js" file as follows:

1. uncomment line 2
2. comment out line 3
3. uncomment line 18
4. comment out line 19

If that doesn't work, then it is possible for you to test and review my code at the official end-of-course state by creating a branch to that commit. Just clone my repo, then create a branch to my commit titled, "Complete debug to reset onscreen playlist and name upon saving," with an SHA of `819b508530e91f5c126ba119031de4eeda918213`. You can do this with the following command:
`git checkout -b officialProject 819b508530e91f5c126ba119031de4eeda918213`
Then you can observe my code before I added all of the additional functionality. Please give it a try and let me know if you can get either of these methods to work to your satisfaction.

**Comment by joshpetras** [comment]
@davecastlevania just calling attention to my previous comment since I forgot to mention you in the post and don't know if you receive notifications if I don't.

**Comment by davecastlevania** [comment]
Please chat us on the Codecademy pro lines about this, thank you.
