### ISSUE TITLE
Codecademy ask me to re-review your project a couple things to point out in here.

### ISSUE THREAD

**Issue by farishkash** [joshpetras/jammming#5]
I looked over David's comments.

First on the initial load I had a problem with the profile picture url.

![jammming1](https://user-images.githubusercontent.com/5844161/34091560-5f8cf448-e373-11e7-8f43-52ebbebfc32b.png)

I don't have a picture.  I commented this out because I really wanted to look at the connect to spotify issue.  This actually helped me figure out what was causing David's issues.

Both of these issues goes hand in hand.  Below is a screenshot after I logged in.  If you see on my screen that connect to spotify is still there and on the right side my display name is null.

![jammming2](https://user-images.githubusercontent.com/5844161/34091927-9330de3e-e375-11e7-85e4-2933240acf96.png)

So after doing this I want to show you the response that is coming from this section of code.

```
connect() {
    Spotify.connect().then(response => {
      if(response.id) {
        this.setState({
          connected: response.display_name,
          profileImage: response.images[0].url
        });
      }
    });
  }
```

![jammming3](https://user-images.githubusercontent.com/5844161/34092024-16253286-e376-11e7-9a40-2d945cc46ee9.png)

The reason why spotify jamming is working for you is you may have a more detail profile than myself or David has.  The table above shows that I have no images and that I have no display name.

Now lets say I just fill out your connect function with strings.

```
connect() {
    Spotify.connect().then(response => {
      if(response.id) {
        this.setState({
          connected: "Farish",
          profileImage: "www.myself.com"
        });
      }
    });
  }

```

It works as normal because we aren't passing through null or an empty value.

![jammming](https://user-images.githubusercontent.com/5844161/34092180-0cfd60ba-e377-11e7-8ab4-afebe4e1c73a.png)

So I thought about this and my idea would be to see if the response values above exist with additional conditional after the  if(response.id) {
for example you could check the Object.values

if (Object.values(response).indexOf('name') > -1)
but there are probably 3 or 4 different ways you can approach this.  Find the one you like.

And then if one of these values doesn't exist I would set connected to the response.id value since that is my user name and then have a default profile image that can be use in cases were the user has none.

This resolves both of David's issues.  

One last thing with regards to ComponentWillMount.  This is suppose to be deprecated.   I would get into habit of using ComponentDidMount instead.  Plus I believe with React Fiber(v 16) this still double calls ComponentWillMount on render.

Project itself is great.  Like that you added your own component and the concept of a connect button.

The only complaint I would say I have is that I use an opinionated way of writing react components following airbnb react style guide.

For example I would take your App.js render method

```
 render() {
    return <div>
        <h1>
          Ja<span className="highlight">mmm</span>ing
        </h1>
        <div className="App">
          <ConnectBtn onConnect={this.connect} onDisconnect={this.disconnect} connected={this.state.connected} imageUrl={this.state.profileImage} />
          <SearchBar onSearch={this.search} connected={this.state.connected} />
          <div className="App-playlist">
            <SearchResults searchResults={this.state.searchResults} onAdd={this.addTrack} />
            <Playlist playlistName={this.state.playlistName} playlistTracks={this.state.playlistTracks} onRemove={this.removeTrack} onNameChange={this.updatePlaylistName} onSave={this.savePlaylist} />
          </div>
        </div>
      </div>;
  }
}

```

and write it like this for what I believe to be better readability.

```
  render() {
    return (
      <div>
        <h1>
          Ja<span className="highlight">mmm</span>ing
        </h1>
        <div className="App">
          <ConnectBtn
            onConnect={this.connect}
            onDisconnect={this.disconnect}
            connected={this.state.connected}
            imageUrl={this.state.profileImage}
          />
          <SearchBar onSearch={this.search} connected={this.state.connected} />
          <div className="App-playlist">
            <SearchResults
              searchResults={this.state.searchResults}
              onAdd={this.addTrack}
            />
            <Playlist
              playlistName={this.state.playlistName}
              playlistTracks={this.state.playlistTracks}
              onRemove={this.removeTrack}
              onNameChange={this.updatePlaylistName}
              onSave={this.savePlaylist}
            />
          </div>
        </div>
      </div>
    );
  }
}
```

**Comment by joshpetras** [comment]
Thanks @farishkash ! Very clear explanation of my code issues! Now I understand what I need to do to fix it. Appreciate the detailed review!
